<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="jakarta.tags.core"%><%@taglib prefix="fmt" uri="jakarta.tags.fmt"%>
<!DOCTYPE html><html><head><title>Product Management</title><%@include file="../common/head.jsp"%></head><body>
<c:set var="pageRole" value="Manager"/><c:set var="pageName" value="Manage Products"/><%@include file="../common/topbar.jsp"%>
<main class="page-shell"><div class="page-heading"><div><h1>Product Management</h1><p>${total} products listed</p></div><a class="btn primary large" href="${pageContext.request.contextPath}/manager/products?action=form">+ Add Product</a></div>
<c:if test="${not empty param.message}"><div class="alert success"><c:out value="${param.message}"/></div></c:if>
<section class="stats-grid"><article><span>TOTAL PRODUCTS</span><strong>${total}</strong><i></i></article><article><span>ACTIVE</span><strong>${active}</strong><i class="green"></i></article><article><span>OUT OF STOCK</span><strong>${outOfStock}</strong><i class="pink"></i></article><article><span>CATEGORIES</span><strong>${categories.size()}</strong><i class="purple"></i></article></section>
<section class="table-panel"><form class="search-row" method="get"><input name="q" value="${param.q}" placeholder="Search name, SKU or barcode..."><select name="brand"><option value="">Brand</option><c:forEach items="${brands}" var="b"><option value="${b.id}" ${selectedBrand==b.id?'selected':''}>${b.name}</option></c:forEach></select><select name="category"><option value="">Category</option><c:forEach items="${categories}" var="c"><option value="${c.id}" ${selectedCategory==c.id?'selected':''}>${c.name}</option></c:forEach></select><button class="btn primary">Search</button></form>
<div class="table-wrap"><table><thead><tr><th>ID</th><th>Product name</th><th>Brand</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<c:forEach items="${products}" var="p"><tr><td class="mono">${p.code}</td><td><strong><c:out value="${p.name}"/></strong><small>${p.sku}</small></td><td>${p.brandName}</td><td><span class="category-chip">${p.categoryName}</span></td><td class="price-small"><fmt:formatNumber value="${p.finalPrice}" pattern="#,##0"/>₫</td><td class="${p.stock==0?'danger':'stock'}">${p.stock}</td><td><span class="status ${p.active?'active':'inactive'}">${p.status}</span></td><td><div class="actions"><a class="btn subtle" href="${pageContext.request.contextPath}/manager/products?action=form&id=${p.id}">Edit</a><form method="post" onsubmit="return confirmDeactivate('product')"><input type="hidden" name="action" value="deactivate"><input type="hidden" name="id" value="${p.id}"><button class="btn danger">Remove</button></form></div></td></tr></c:forEach>
</tbody></table></div></section></main><script src="${pageContext.request.contextPath}/assets/js/store.js"></script></body></html>
