<%@page contentType="text/html" pageEncoding="UTF-8"%><%@taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html><html><head><title>${product.id==0?'Add':'Edit'} Product</title><%@include file="../common/head.jsp"%></head><body>
<c:set var="pageRole" value="Manager"/><c:set var="pageName" value="${product.id==0?'Add Product':'Edit Product'}"/><%@include file="../common/topbar.jsp"%>
<main class="page-shell narrow"><div class="page-heading"><div><h1>${product.id==0?'Add Product':'Edit Product'}</h1><p>Fields marked * are required</p></div><a class="btn subtle" href="${pageContext.request.contextPath}/manager/products">← Back</a></div>
<c:if test="${not empty error}"><div class="alert error"><c:out value="${error}"/></div></c:if>
<form class="entity-form" method="post"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="${product.id}">
<div class="form-grid"><label class="span-2">Product name *<input name="name" maxlength="50" value="<c:out value='${product.name}'/>" required></label><label>Brand *<select name="brandId" required><option value="">Choose brand</option><c:forEach items="${brands}" var="b"><option value="${b.id}" ${product.brandId==b.id?'selected':''}>${b.name}</option></c:forEach></select></label><label>Category *<select name="categoryId" required><option value="">Choose category</option><c:forEach items="${categories}" var="c"><option value="${c.id}" ${product.categoryId==c.id?'selected':''}>${c.name}</option></c:forEach></select></label>
<label>SKU *<input name="sku" maxlength="100" value="<c:out value='${product.sku}'/>" required></label><label>Barcode *<input name="barcode" maxlength="100" value="<c:out value='${product.barcode}'/>" required></label><label>Selling price *<input type="number" name="sellingPrice" min="0" value="${product.sellingPrice}" required></label><label>Latest cost *<input type="number" name="latestCost" min="0" value="${product.latestCost}" required></label>
<label>Stock *<input type="number" name="stock" min="0" value="${product.stock}" required></label><label>Release year<input type="number" name="releaseYear" min="2000" max="2100" value="${product.releaseYear}"></label><label>Warranty (months)<input type="number" name="warrantyMonths" min="0" value="${product.warrantyMonths==0?12:product.warrantyMonths}"></label>
<label>Rating<select name="rating"><c:forEach begin="0" end="5" var="i"><option value="${i}" ${product.rating==i?'selected':''}>${i}</option></c:forEach></select></label><label>Status<select name="status"><option value="ACTIVE" ${product.active?'selected':''}>Active</option><option value="INACTIVE" ${!product.active&&product.id>0?'selected':''}>Inactive</option></select></label><label class="span-2">Image path / URL<input name="image" maxlength="255" value="<c:out value='${product.image}'/>" placeholder="/assets/images/products/phone.jpg"></label><label class="span-2">Description<textarea name="description" maxlength="255" rows="4"><c:out value="${product.description}"/></textarea></label></div>
<div class="form-actions"><a class="btn subtle" href="${pageContext.request.contextPath}/manager/products">Cancel</a><button class="btn primary large">Save Product</button></div></form></main></body></html>
